In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [5]:
df.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1,inplace=True)

In [6]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
from sklearn.preprocessing import LabelEncoder   

label_gender=LabelEncoder()  
df['Gender']=label_gender.fit_transform(df['Gender'])

In [8]:
df['Gender']

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int32

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  int32
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int32(1), int64(7), str(1)
memory usage: 879.1 KB

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
one_hot_geo=OneHotEncoder() 
geo_encoded=one_hot_geo.fit_transform(df[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [12]:
geo_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
one_hot_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
df_geo=pd.DataFrame(geo_encoded.toarray(),columns=one_hot_geo.get_feature_names_out(['Geography']))
df_geo

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [16]:
df.drop(['Geography'],axis=1,inplace=True)

In [17]:
dfn=pd.concat([df,df_geo],axis=1)

In [18]:
dfn

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [19]:
import pickle as pkl  
with open('label_gender.pkl','wb') as file: 
    pkl.dump(label_gender,file)

In [20]:
with open('one_hot_geo.pkl','wb') as file : 
    pkl.dump(one_hot_geo,file)

In [21]:
dfn.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [22]:
from sklearn.preprocessing import StandardScaler   
from sklearn.model_selection import train_test_split  
x=dfn.drop(['Exited'],axis=1) 
y=dfn['Exited']

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42) 
x_train.shape,y_train.shape

((8000, 12), (8000,))

In [24]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train) 
x_test=sc.transform(x_test)

In [25]:
with open("Scaler.pkl",'wb') as file: 
    pkl.dump(sc,file)

In [26]:
#ANN 

import tensorflow

WARNING:tensorflow:From e:\DLproject1\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [27]:
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

from tensorflow.keras.models import Sequential

In [28]:
model=Sequential([
    Dense(32,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(16,activation='relu'),
    Dense(1,activation='sigmoid')])

WARNING:tensorflow:From e:\DLproject1\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [29]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss=tensorflow.keras.losses.BinaryCrossentropy()
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [30]:
#tensor board is visualization tool to visualize the all mention function

In [31]:
import datetime

In [32]:
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping

In [33]:
log_dir='log/fit/' +datetime.datetime.now().strftime('%y%m%d-%H%M%S')

In [34]:
tensorflow_callback=TensorBoard(log_dir,histogram_freq=1)

In [35]:
early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [36]:
history=model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test),callbacks=[tensorflow_callback,early_stopping_callbacks])

Epoch 1/100
WARNING:tensorflow:From e:\DLproject1\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\DLproject1\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 0.4886 - accuracy: 0.7794 - val_loss: 0.4165 - val_accuracy: 0.8145
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4118 - accuracy: 0.8253 - val_loss: 0.3817 - val_accuracy: 0.8410
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3791 - accuracy: 0.8440 - val_loss: 0.3592 - val_accuracy: 0.8500
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3586 - accuracy: 0.8520 - val_loss: 0.3482 - val_accuracy: 0.8530
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3487 - accuracy: 0.8558 - val_loss: 0.3448 - val_accuracy: 0.8550
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3439 - accuracy: 0.8574 - val_loss: 0.3455 - val_accuracy: 0.8610
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3405 - accuracy: 0.8615 - val_loss: 0.3437 - val_accuracy: 0.8590
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3373 - accuracy: 0.8601 - val_loss: 0.3463 - val_accuracy: 0.8575
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3352 - accuracy: 0.8620 - val_loss: 0.3445 - val_accuracy: 0.8565
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3324 - accuracy: 0.8631 - val_loss: 0.3426 - val_accuracy: 0.8570
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8636 - val_loss: 0.3433 - val_accuracy: 0.8560
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3301 - accuracy: 0.8641 - val_loss: 0.3505 - val_accuracy: 0.8575
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3283 - accuracy: 0.8655 - val_loss: 0.3456 - val_accuracy: 0.8635
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3276 - accuracy: 0.8640 - val_loss: 0.3427 - val_accuracy: 0.8595
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3265 - accuracy: 0.8640 - val_loss: 0.3411 - val_accuracy: 0.8570
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3242 - accuracy: 0.8661 - val_loss: 0.3418 - val_accuracy: 0.8575
Epoch 17/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3236 - accuracy: 0.8643 - val_loss: 0.3441 - val_accuracy: 0.8580
Epoch 18/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3235 - accuracy: 0.8664 - val_loss: 0.3402 - val_accuracy: 0.8565
Epoch 19/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3227 - accuracy: 0.8681 - val_loss: 0.3456 - val_accuracy: 0.8545
Epoch 20/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3212 - accuracy: 0.8686 - val_loss: 0.3438 - val_accuracy: 0.8625
Epoch 21/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3210 - accuracy: 0.8654 - val_loss: 0.3398 - val_accuracy: 0.8610
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3197 - accuracy: 0.8691 - val_loss: 0.3412 - val_accuracy: 0.8615
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3191 - accuracy: 0.8674 - val_loss: 0.3423 - val_accuracy: 0.8575
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3187 - accuracy: 0.8680 - val_loss: 0.3432 - val_accuracy: 0.8560
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3181 - accuracy: 0.8689 - val_loss: 0.3424 - val_accuracy: 0.8575
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3172 - accuracy: 0.8680 - val_loss: 0.3405 - val_accuracy: 0.8605

In [37]:
model.save("churn_model.h5")

e:\DLproject1\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [38]:
%load_ext tensorboard
%tensorboard --logdir log/fit

Reusing TensorBoard on port 6006 (pid 10700), started 8:37:44 ago. (Use '!kill 10700' to kill it.)

In [39]:
!taskkill /f /pid 10700

ERROR: The process "10700" not found.