In [4]:
import pandas as pd
import numpy as np 
import pickle as p
import tensorflow as tf
from tensorflow.keras.models import load_model

In [5]:
model=load_model('churn_model.h5')

In [6]:
with open('label_gender.pkl','rb') as file:
    label_encoder_gender=p.load(file)

In [7]:
with open('one_hot_geo.pkl','rb') as file:
    one_hot_geo=p.load(file)

In [9]:
with open('Scaler.pkl','rb') as file:
    Scaler=p.load(file)

In [10]:
#  Sample data 
input_data = {

'CreditScore':600,

'Geography': 'France',

'Gender': 'Male',

'Age': 40,

'Tenure': 3,

'Balance':60000,

'NumOfProducts': 2,

'HasCrCard':1,

'IsActiveMember': 1,

'EstimatedSalary': 50000

}

In [11]:
geo_encoder=one_hot_geo.transform([[input_data['Geography']]]).toarray()

e:\DLproject1\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [12]:
geo_encoder

array([[1., 0., 0.]])

In [14]:
geo_df=pd.DataFrame(geo_encoder,columns=one_hot_geo.get_feature_names_out(['Geography']))

In [15]:
geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [16]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [17]:
input_df['Gender']=label_encoder_gender.transform([input_data['Gender']])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [18]:
input_df.drop('Geography',axis=1,inplace=True)

In [19]:
df=pd.concat([input_df,geo_df],axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [20]:
input_scaled=Scaler.transform(df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [21]:
pred=model.predict(input_scaled)
pred

1/1 [==============================] - 0s 208ms/step

array([[0.04402172]], dtype=float32)

In [ ]:
pred[0][0]    # 0 leave, 1 stay

0.044021722

In [23]:
if pred[0][0]>0.5:
    print('Customer will leave')
else:
    print('Customer will stay')

Customer will stay